FROM node:latest

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install

COPY . .

ENV NEW_RELIC_NO_CONFIG_FILE=true
ENV NEW_RELIC_APP_NAME="TimeToGlass"

# VARIALBLES TO FILL-IN
ENV NEW_RELIC_LICENSE_KEY=""
ENV NEWRELIC_ACCOUNT_ID=
ENV NEWRELIC_INSERT_KEY=""
ENV NEWRELIC_USER_API_KEY=""
ENV NEWRELIC_LOCATION="US"

CMD [ "node", "index.js" ]