FROM node:latest

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install

COPY . .

ENV NEW_RELIC_NO_CONFIG_FILE=true
ENV NEW_RELIC_APP_NAME="TimeToGlass"

# VARIALBLES TO FILL-IN
ENV NEW_RELIC_LICENSE_KEY=YOURLICENCEKEY
ENV NEWRELIC_ACCOUNT_ID=YOURACCOUNTID
ENV NEWRELIC_INSERT_KEY='YOURINSERTKEY'
ENV NEWRELIC_QUERY_KEY='YOURQUERYKEY'
ENV NEWRELIC_LOCATION='China'

CMD [ "node", "index.js" ]